In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

df = pd.DataFrame(data)
print(df.head())

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [2]:
df = pd.read_csv("Mall_Customers.csv")
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
df.tail()

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

In [6]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [7]:
df['Age']
df[['Genre', 'Age']]        
df.iloc[2]                 
df.loc[4]

CustomerID                     5
Genre                     Female
Age                           31
Annual Income (k$)            17
Spending Score (1-100)        40
Name: 4, dtype: object

In [8]:
df[df['Age'] > 30]                          
df[df['Spending Score (1-100)'] == '50']                 
df[(df['Age'] > 25) & (df['Genre'] == 'Male')]

     CustomerID Genre  Age  Annual Income (k$)  Spending Score (1-100)
8             9  Male   64                  19                       3
10           11  Male   67                  19                      14
14           15  Male   37                  20                      13
18           19  Male   52                  23                      29
20           21  Male   35                  24                      35
..          ...   ...  ...                 ...                     ...
187         188  Male   28                 101                      68
192         193  Male   33                 113                       8
197         198  Male   32                 126                      74
198         199  Male   32                 137                      18
199         200  Male   30                 137                      83

[70 rows x 5 columns]

In [9]:
df[df['Spending Score (1-100)'] =='100']

Empty DataFrame
Columns: [CustomerID, Genre, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

In [15]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [14]:
df.dropna(inplace=True)

In [11]:
df['Age'].value_counts()

Age
32    11
35     9
19     8
31     8
30     7
49     7
23     6
40     6
36     6
27     6
47     6
38     6
21     5
20     5
29     5
48     5
50     5
34     5
67     4
24     4
54     4
18     4
59     4
28     4
22     3
37     3
25     3
46     3
45     3
60     3
33     3
43     3
68     3
39     3
58     2
52     2
53     2
42     2
65     2
51     2
70     2
63     2
26     2
57     2
66     2
44     2
41     2
64     1
69     1
55     1
56     1
Name: count, dtype: int64

In [12]:
df.groupby('Genre')['Age'].mean()

Genre
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [13]:
df.to_csv('cleaned_data.csv', index=False)